export default [
    [{
        'question': 'Portland\'s name was decided by a coin toss.  After which city was it almost named?',
        'category': 'social',
        'level': 1,
        'answerA': 'Hanover',
        'answerB': 'Syracuse',
        'answerC': 'Manchester',
        'answerD': 'Boston',
        'correctAnswer': 'D',
    },
    {
        'question': 'Portland\'s smallest park comes in at 2.5 feet in diameter.  What\'s its name?',
        'category': 'landmarks',
        'level': 2,
        'answerA': 'Director Park',
        'answerB': 'Mill Ends Park',
        'answerC': 'O\'Bryant Square',
        'answerD': 'Dawson Park',
        'correctAnswer': 'B',
    },
    {
        'question': 'At which Portland food establishment can you also get married?',
        'category': 'culture',
        'level': 1,
        'answerA': 'Jake\'s Famous Crawfish Seafood Restaurant',
        'answerB': 'Voodoo Donuts',
        'answerC': 'Laughing Planet',
        'answerD': 'Portland City Grill',
        'correctAnswer': 'B',
    },
    {
        'question': 'Which supernatural TV series was filmed in Portland?',
        'category': 'social',
        'level': 1,
        'answerA': 'Grimm',
        'answerB': 'Supernatural',
        'answerC': 'True Blood',
        'answerD': 'Sense8',
        'correctAnswer': 'A',
    },
    {
        'question': 'What neighborhood in Portland is at odds with the rectilinear grid followed by the rest of the city?',
        'category': 'landmarks',
        'level': 1,
        'answerA': 'Sunnyside',
        'answerB': 'Laurelhurst',
        'answerC': 'Ladd\'s Addition',
        'answerD': 'Irvington',
        'correctAnswer': 'C',
    },
    {
        'question': 'What month long festival each June celebrates bikes?',
        'category': 'culture',
        'level': 1,
        'answerA': 'Cyclepalooza',
        'answerB': 'Bikers Unite',
        'answerC': 'Pedalpalooza',
        'answerD': 'Bike Fest',
        'correctAnswer': 'C',
    },   
    {
        'question': 'What NPR host and Portland native occasionally tours with Pink Martini?',
        'category': 'social',
        'level': 1,
        'answerA': 'Audie Cornish',
        'answerB': 'Scott Simon',
        'answerC': 'Ari Shapiro',
        'answerD': 'Terry Gross',
        'correctAnswer': 'C',
    },
    {
        'question': 'What extinct volcano lies within the Portland city limits?',
        'category': 'landmarks',
        'level': 1,
        'answerA': 'Mt. Tabor',
        'answerB': 'Rocky Butte',
        'answerC': 'Powell Butte',
        'answerD': 'Kelly Butte',
        'correctAnswer': 'A',
    },
    {
        'question': 'Portland loves its coffee.  Per capita, in which area does it lead the nation?',
        'category': 'culture',
        'level': 1,
        'answerA': 'coffee roasters',
        'answerB': 'coffee shops',
        'answerC': 'baristas',
        'answerD': 'carts',
        'correctAnswer': 'A'
    }],
// Level 2
    [{
        'question': 'What Portland establishment includes a 21 foot chocolate waterfall?',
        'category': 'landmarks',
        'level': 2,
        'answerA': 'Moonstruck',
        'answerB': 'Woodblock',
        'answerC': 'The Candy Basket',
        'answerD': 'Cacao',
        'correctAnswer': 'C',
    },
    {
        'question': 'Since 1912 these water fountains have provided free water to thirsty Portlanders.  They are?',
        'category': 'landmarks',
        'level': 3,
        'answerA': 'Lovejoy Fountains',
        'answerB': 'Failing Fountains',
        'answerC': 'Overton Bubblers',
        'answerD': 'Benson Bubblers',
        'correctAnswer': 'D',
    },
    {
        'question': 'The White Stag sign on the Willamette River initially advertised what?',
        'category': 'landmarks',
        'level': 2,
        'answerA': 'sugar',
        'answerB': 'beer',
        'answerC': 'salt',
        'answerD': 'clothing',
        'correctAnswer': 'A',
    },
    {
        'question': 'What Portland author won the Hugo, Nebula, Locus and World Fantasy Awards?',
        'category': 'social',
        'level': '2',
        'answerA': 'Jean Auel',
        'answerB': 'Arthur C. Clarke',
        'answerC': 'Orson Scott Card',
        'answerD': 'Ursula LeGuin',
        'correctAnswer': 'D',
    },
    {
        'question': 'Portlander Ward Cunningham developed ______ in 1995 leading ______ to celebrate it\'s 10 year anniversary here.',
        'category': 'social',
        'level': '2',
        'answerA': 'the wiki, Wikipedia',
        'answerB': 'microbrewing, Craft Brewing Council',
        'answerC': 'the WWW, Google',
        'answerD': 'lasik, FDA Division of Opthalmic Devices',
        'correctAnswer': 'A'
    },
    {
        'question': 'What Portland singer competed on the television show "Rock Star Supernova"?',
        'category': 'social',
        'level': 2,
        'answerA': 'James Mercer',
        'answerB': 'Storm Large',
        'answerC': 'China Forbes',
        'answerD': 'Art Alexakis',
        'correctAnswer': 'B',
    },
    {
        'question': 'Portland has more of these, per capita than any other city in the US.',
        'category': 'culture',
        'level': 2,
        'answerA': 'tall bikes and scooters',
        'answerB': 'strip clubs and microbreweries',
        'answerC': 'coffee shops and bookstores',
        'answerD': 'yarn stores and brew pubs',
        'correctAnswer': 'B'
    },
    {
        'question': 'Every year Mt. Tabor is the location for what competition?',
        'category': 'culture',
        'level': 2,
        'answerA': 'hula hoop',
        'answerB': 'yoga',
        'answerC': 'soapbox derby',
        'answerD': 'pogo stick',
        'correctAnswer': 'C' 
    },
    {
        'question': 'What Portland bike ride attracts upwards of 10,000 participants?',
        'category': 'culture',
        'level': 2,
        'answerA': 'Starlight Ride',
        'answerB': 'Tall Bike Gathering',
        'answerC': 'Worst Day of the Year Ride',
        'answerD': 'World Naked Bike Ride',
        'correctAnswer': 'D'
    }],
// Level 3
    [{
        'question': 'The oldest vehicular bridge across the Willamette River is the?',
        'category': 'landmarks',
        'level': 3,
        'answerA': 'Burnside Bridge',
        'answerB': 'Morrison Bridge',
        'answerC': 'Hawthorne Bridge',
        'answerD': 'Sellwood Bridge',
        'correctAnswer': 'C',
    },
    {
        'question': 'What statue is Portland is the second largest hammered copper sculpture in the US behind the Statue of Liberty?',
        'category': 'landmarks',
        'level': 3,
        'answerA': 'Portlandia',
        'answerB': 'Joan of Arc',
        'answerC': 'Sacajawea and Jean-Baptiste',
        'answerD': 'The Dream',
        'correctAnswer': 'A',
    },
    {
        'question': 'Why do the downtown streets on either side of Burnside come in at different angles?',
        'category': 'landmarks',
        'level': 3,
        'answerA': 'The river curves and the streets are parallel to the river.',
        'answerB': 'Downtown was platted on magnetic north and the Pearl on true north.',
        'answerC': 'There was no overall plan for the city.',
        'answerD': 'One of the survey crews got its baseline wrong and the mistake was discovered too late.',
        'correctAnswer': 'B',
    },
    {
        'question': 'What rum drink was created in Portland in 1944 by Vic Bergeron?',
        'category': 'culture',
        'level': 3,
        'answerA': 'Hurricane',
        'answerB': 'Mai Tai',
        'answerC': 'Dark & Stormy',
        'answerD': 'Cable Car',
        'correctAnswer': 'B'
    },
    {
        'question': 'Where in Portland can you ride a 5/8 scale narrow gauge railroad?',
        'category': 'culture',
        'level': 3,
        'answerA': 'Oaks Park',
        'answerB': 'Willamette Short Trolley',
        'answerC': 'Oregon Pacific Railroad',
        'answerD': 'Oregon Zoo',
        'correctAnswer': 'D'
    },
    {
        'question': 'Who can be spotted riding around Portland on a unicycle while playing bagpipes and wearing a Darth Vader mask?',
        'category': 'culture',
        'level': 3,
        'answerA': 'the Unipiper',
        'answerB': 'Darth Piper',
        'answerC': 'McVader',
        'answerD': 'Scotty',
        'correctAnswer': 'A'
    },
    {
        'question': 'What Portland church was founded in opposition to a Kansas decision to teach intelligent design',
        'category': 'social',
        'level': 3,
        'answerA': 'Church of Elvis',
        'answerB': 'Church of Raëlism',
        'answerC': 'Church of the Flying Spaghetti Monster',
        'answerD': 'Seventh Day Bicyclists',
        'correctAnswer': 'C'
    },
    {
        'question': 'Which Portland author\'s novel about hiking the Pacific Crest Trail was made into a movie starring Reese Witherspoon',
        'category': 'social',
        'level': 3,
        'answerA': 'Richard Meltzer',
        'answerB': 'April Henry',
        'answerC': 'Terence O\'Donnell',
        'answerD': 'Cheryl Strayed',
        'correctAnswer': 'D'
    },
    {
        'question': 'An international knitting conference focused on ________ attracted over 6000 participants to Portland in 2009 and again in 2011.',
        'category': 'social',
        'level': 3,
        'answerA': 'sweaters',
        'answerB': 'socks',
        'answerC': 'scarves',
        'answerD': 'hats',
        'correctAnswer': 'B'
    }]
];